
CREATE TABLE SENATOR
(
    `NAME` VARCHAR(256) BINARY NOT NULL,
    PARTY VARCHAR(256) BINARY NULL,
    URL VARCHAR(256) BINARY NULL,
    PRIMARY KEY (`NAME`)
) ENGINE=INNODB;

CREATE TABLE `USER`
(
    EMAIL VARCHAR(256) BINARY NOT NULL,
    AUTH VARCHAR(256) BINARY NULL,
    FIRST_NAME VARCHAR(256) BINARY NULL,
    LAST_NAME VARCHAR(256) BINARY NULL,
    SUBS LONG VARBINARY NULL,
    PRIMARY KEY (EMAIL)
) ENGINE=INNODB;

